/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-ui/lib/button')['default']
    ElPagination: typeof import('element-ui/lib/pagination')['default']
    ElTable: typeof import('element-ui/lib/table')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/Table/Table.vue')['default']
  }
}
